name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    - name: Pull Master Branch
      run: |
        cd /var/www/puzztory/ && sudo git pull origin master
    - name: Pull Master Branch
      run: |
        cd /var/www/puzztory/ && sudo yarn build
    - name: Restart server
      run: |
        sudo systemctl restart nginx
